### ISSUE TITLE
Is this the latest code for Brian->LEMS?

### ISSUE THREAD

**Issue by pgleeson** [brian-team/gsoc2016#12]
@mstimberg Just checking whether this is the latest version of code for exporting Brian models to LEMS.

If so, we can (slowly, low priority...) update it, and add information here: https://docs.neuroml.org/Userdocs/Software/Tools/Brian.html#userdocs-brian with what's currently supported.

**Comment by mstimberg** [comment]
Hi @pgleeson No, the latest version is part of https://github.com/brian-team/brian2tools
In particular, see https://brian2tools.readthedocs.io/en/latest/user/nmlexporter.html

**Comment by pgleeson** [comment]
Just saw it there... Thanks!
