### ISSUE TITLE
record=True in Spike/State monitors

### ISSUE THREAD

**Issue by dokato** [brian-team/gsoc2016#3]
When `record=True` in monitors logical thing to do would be to add as many `Line`s to `Display` and as many `EventSelection` as there are neurons. But if the number is big it may cause some memory problems in the future I guess.

**Comment by mstimberg** [comment]
Regardless of whether the user specified explicit indices or `record=True`, `StateMonitor.record` will be an array of the indices to record, i.e. this is what you should use. For `SpikeMonitor`, yes, record all neurons. Do not worry about big networks, this is not what LEMS/NeuroML is currently made for. With synapses, we cannot have too big networks anyway (e.g. for testing, use CUBA/COBAHH with, say, 80 instead of 4000 neurons

**Comment by dokato** [comment]
> StateMonitor.record will be an array of the indices to record, i.e. this is what you should use. 

Is it really like this? I tried to iterate over `obj.record` but in the case of record=True I got:

``` python
TypeError: 'bool' object is not iterable
```

So instead I implemented it like this:

``` python
        indices = obj.record
        if isinstance(indices, bool) and indices == True:
            indices = np.arange(self._nr_of_neurons)
        indices += 1
```

**Comment by mstimberg** [comment]
Hmm, this is weird. If you look at the code in `StateMonitor.__init__`, it should either replace the `True` by the values or raise a `NotImplementedError`:

``` Python
        if record is True:
            self.record_all = True
            try:
                record = np.arange(len(source), dtype=np.int32)
            except NotImplementedError:
                # In standalone mode, this is not possible for synaptic
                # variables because the number of synapses is not defined yet
                raise NotImplementedError(('Cannot determine the actual '
                                           'indices to record for record=True. '
                                           'This can occur for example in '
                                           'standalone mode when trying to '
                                           'record a synaptic variable. '
                                           'Consider providing an explicit '
                                           'array of indices for the record '
                                           'argument.'))
        elif record is False:
            record = np.array([], dtype=np.int32)
        elif isinstance(record, numbers.Number):
            record = np.array([record], dtype=np.int32)
        else:
            record = np.asarray(record, dtype=np.int32)

        #: The array of recorded indices
        self.record = record
```

**Comment by dokato** [comment]
works with indices
