### ISSUE TITLE
Implement automatic tests

### ISSUE THREAD

**Issue by mstimberg** [brian-team/gsoc2016#5]
With the monitors writing to disk, it should now be possible to run the same simulation with Brian 2 and with LEMS and then compare the stored voltage traces and/or spikes.

**Comment by pgleeson** [comment]
When this is working I can add examples of Brian/generated LEMS to the BrianShowcase repo and add [OMV](https://github.com/OpenSourceBrain/osb-model-validation) tests on exact spike times etc. See here: https://travis-ci.org/OpenSourceBrain/BrianShowcase/builds/149162751

**Comment by dokato** [comment]
done (look at `test_recordings.py`)
