### ISSUE TITLE
Build automatically when `run` is encountered

### ISSUE THREAD

**Issue by mstimberg** [brian-team/gsoc2016#7]
Have a look at `CPPStandaloneDevice`, it has an option `build_on_run` which defaults to `True`. With this option activated, it will call `build` automatically at the end of `network_run`. In `LEMSDevice`, this also makes sense, in particular if we only support a single `run` statement -- this will save the user some typing, adding the `set_device` would be the only change needed to switch from a standard run to LEMS/NeuroML generation. The output file name can be set directly in `set_device` (again, have a look at `CPPStandaloneDevice`).

**Comment by dokato** [comment]
Ok, after studying that code http://brian2.readthedocs.io/en/2.0rc3/_modules/brian2/devices/cpp_standalone/device.html#CPPStandaloneDevice adding `build_on_run` wasn't difficult, but I couldn't find any example with extra parameters in `set_device`.  Even above has empty init: `__init__(self)` and the only example using `CPPStandaloneDevice` uses old approach with `build`.

**Comment by mstimberg** [comment]
`set_device` calls `Device.activate` for the chosen device and this stores all arguments in `Device.build_options`: http://brian2.readthedocs.io/en/2.0rc3/_modules/brian2/devices/device.html#Device.activate
You therefore should not have to do anything, the `build_options` dictionary has all you need.
The following example uses the approach to set the directory and does not have an explicit `build` call: http://brian2.readthedocs.io/en/2.0rc3/examples/standalone.STDP_standalone.html

**Comment by dokato** [comment]
I don't know if I'm missing something but it seems that `CPPStandaloneDevice` has `self.build_on_run = False`. See here:

https://github.com/brian-team/brian2/blob/81af957d6b9dacd919393c355c2f48f1d26a2562/brian2/devices/cpp_standalone/device.py#L133

And in my case setting `self.build_on_run = True` didn't change anything. Still I need to call `build` method. Maybe value of `build_on_run` is changed at some point, but not sure where exactly.

**Comment by mstimberg** [comment]
> I don't know if I'm missing something but it seems that CPPStandaloneDevice has self.build_on_run = False

This could be more obvious, indeed... `build_on_run` is an argument of the `set_device` function and has the default value of `True` which is then passed on to `Device.activate`:
https://github.com/brian-team/brian2/blob/81af957d6b9dacd919393c355c2f48f1d26a2562/brian2/devices/device.py#L513

The `activate` method sets the `build_on_run` argument accordingly:
https://github.com/brian-team/brian2/blob/81af957d6b9dacd919393c355c2f48f1d26a2562/brian2/devices/device.py

The whole logic behind switching devices (using the `activate`, etc.) is unfortunately quite complicated. The main reason is that we switch devices quite often (e.g. to evaluate subexpressions in standalone mode; during testing) and this should not forget about previously set options.

> And in my case setting self.build_on_run = True didn't change anything. Still I need to call build method. Maybe value of build_on_run is changed at some point, but not sure where exactly.

You'll have to manually check this attribute in `network_run` and call `self.build` if it is set to true, same as the standalone device does:
https://github.com/brian-team/brian2/blob/81af957d6b9dacd919393c355c2f48f1d26a2562/brian2/devices/cpp_standalone/device.py#L1106

**Comment by dokato** [comment]
Ok, it works now.
